format = """
$username\
$directory\
$git_branch\
$git_status\
$fill\
$c\
$elixir\
$elm\
$golang\
$haskell\
$java\
$julia\
$nodejs\
$nim\
$rust\
$scala\
$conda\
$python\
$time\n  \
[󱞪](fg:lavender) \
"""

palette = "catppuccin_macchiato"

[palettes.rose-pine]
overlay = '#26233a'
love = '#eb6f92'
gold = '#f6c177'
rose = '#ebbcba'
pine = '#31748f'
foam = '#9ccfd8'
iris = '#c4a7e7'

[palettes.catppuccin_macchiato]
rosewater = "#f4dbd6"
flamingo = "#f0c6c6"
pink = "#f5bde6"
mauve = "#c6a0f6"
red = "#ed8796"
maroon = "#ee99a0"
peach = "#f5a97f"
yellow = "#eed49f"
green = "#a6da95"
teal = "#8bd5ca"
sky = "#91d7e3"
sapphire = "#7dc4e4"
blue = "#8aadf4"
lavender = "#b7bdf8"
text = "#cad3f5"
subtext1 = "#b8c0e0"
subtext0 = "#a5adcb"
overlay2 = "#939ab7"
overlay1 = "#8087a2"
overlay0 = "#6e738d"
surface2 = "#5b6078"
surface1 = "#494d64"
surface0 = "#363a4f"
base = "#24273a"
mantle = "#1e2030"
crust = "#181926"

[username]
disabled = false
format = "[](fg:surface0)[ 󰄛 $user ]($style)[](fg:surface0) "
show_always = true
style_root = "bg:surface0 fg:mauve"
style_user = "bg:surface0 fg:mauve"

[directory]
format = "[](fg:surface0)[ $path ]($style)[](fg:surface0) "
style = "bg:surface0 fg:pink"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
Documents = "󰈙"
Downloads = " "
Music = " "
Pictures = " "

[git_branch]
format = "[](fg:surface0)[ $symbol $branch ]($style)[](fg:surface0) "
style = "bg:surface0 fg:pink"
symbol = ""

[git_status]
disabled = false
style = "bg:surface0 fg:flamingo"
format = '[](fg:surface0)([$all_status$ahead_behind]($style))[](fg:surface0) '
up_to_date = '[ ✓ ](bg:surface0 fg:green)'
untracked = '[?\($count\)](bg:surface0 fg:yellow)'
stashed = '[\$](bg:surface0 fg:green)'
modified = '[!\($count\)](bg:surface0 fg:yellow)'
renamed = '[»\($count\)](bg:surface0 fg:green)'
deleted = '[✘\($count\)](style)'
staged = '[++\($count\)](bg:surface0 fg:yellow)'
ahead = '[⇡\(${count}\)](bg:surface0 fg:teal)'
diverged = '⇕[\[](bg:surface0 fg:green)[⇡\(${ahead_count}\)](bg:surface0 fg:teal)[⇣\(${behind_count}\)](bg:surface0 fg:peach)[\]](bg:surface0 fg:green)'
behind = '[⇣\(${count}\)](bg:surface0 fg:peach)'

[fill]
style = "fg:surface0"
symbol = " "

[time]
disabled = false
format = "[](fg:surface0)[ $time 󱑒 ]($style)[](fg:surface0)"
style = "bg:surface0 fg:blue"
time_format = "%I:%M%P"
use_12hr = true

# Languages

[c]
style = "bg:surface0 fg:sapphire"
format = "[](fg:surface0)[$symbol$version]($style)[](fg:surface0) "
disabled = false
symbol = " "

[elixir]
style = "bg:surface0 fg:sapphire"
format = "[](fg:surface0)[$symbol$version]($style)[](fg:surface0) "
disabled = false
symbol = " "

[elm]
style = "bg:surface0 fg:sapphire"
format = "[](fg:surface0)[$symbol$version]($style)[](fg:surface0) "
disabled = false
symbol = " "

[golang]
style = "bg:surface0 fg:sapphire"
format = "[](fg:surface0)[$symbol$version]($style)[](fg:surface0) "
disabled = false
symbol = " "

[haskell]
style = "bg:surface0 fg:sapphire"
format = "[](fg:surface0)[$symbol$version]($style)[](fg:surface0) "
disabled = false
symbol = " "

[java]
style = "bg:surface0 fg:sapphire"
format = "[](fg:surface0)[$symbol$version]($style)[](fg:surface0) "
disabled = false
symbol = " "

[julia]
style = "bg:surface0 fg:sapphire"
format = "[](fg:surface0)[$symbol$version]($style)[](fg:surface0) "
disabled = false
symbol = " "

[nodejs]
style = "bg:surface0 fg:sapphire"
format = "[](fg:surface0)[$symbol$version]($style)[](fg:surface0) "
disabled = false
symbol = "󰎙 "

[nim]
style = "bg:surface0 fg:sapphire"
format = "[](fg:surface0)[$symbol$version]($style)[](fg:surface0) "
disabled = false
symbol = "󰆥 "

[rust]
style = "bg:surface0 fg:sapphire"
format = "[](fg:surface0)[$symbol$version]($style)[](fg:surface0) "
disabled = false
symbol = ""

[scala]
style = "bg:surface0 fg:sapphire"
format = "[](fg:surface0)[$symbol$version]($style)[](fg:surface0) "
disabled = false
symbol = " "

[python]
style = "bg:surface0 fg:sapphire"
format = "[](fg:surface0)[$symbol$version]($style)[](fg:surface0) "
disabled = false
symbol = ' '

[conda]
style = "bg:surface0 fg:sapphire"
format = "[](fg:surface0)[$symbol$environment]($style)[](fg:surface0) "
disabled = false
symbol = '🅒 '
