"$schema" = "https://starship.rs/config-schema.json"

palette = 'catppuccin_macchiato'

format = """
[▒▓](mantle)\
$username\
$directory\
[ ](fg:lavender)\
$git_branch\
$git_status\
[ ](fg:lavender)\
"""

right_format = """
$cmd_duration\
$nodejs\
$battery\
"""

add_newline = true

[username]
show_always = true
style = "fg:lavender bg:mantle"

[os]
disabled = false
style = "bg:color_mantle fg:color_text"

[cmd_duration]
min_time = 1_000
show_notifications = false
min_time_to_notify = 10_000

show_milliseconds = true
format = '[$duration ]($style)'
style = 'fg:color_pink bg:color_mantle'

[custom.is_folder_config]
disabled = true
when = "echo $PWD | grep -q '/.config'"
symbol = ' '
format = '[$symbol]($style)'
style = 'fg:color_blue bg:color_mantle'

[env_var.shell]
disabled = true
symbol = ''
variable = 'SHELL'
format = '[($symbol $env_value )]($style)'
style = 'fg:color_lavender bg:color_mantle'

[shell]
disabled = true

[custom.nvim]
disabled = true
when = "echo $PWD | grep -q '.config/nvim'"
symbol = ' '
format = '[$symbol($output )]($style)'
style = 'fg:color_lavender bg:color_mantle'
command = "nvim --version | head -n 1 | tr ' ' '\n' | tail -n 1"

[meson]
symbol = 'Meson: '
format = '[$symbol(\($project\) )]($style)'
style = 'fg:color_lavender bg:color_mantle'



[directory]
truncate_to_repo = true
format = '[([$read_only ]($style fg:color_red))$path ]($style)'
style = 'fg:color_text bg:color_mantle'
truncation_length = 5
read_only = ''

[git_branch]
# symbol = ''
symbol = ''
format = '[$symbol $branch(:$remote_branch) ]($style)'
style = 'fg:color_red bg:color_mantle'

[git_status]
disabled = true

[git_commit]
disabled = false
only_detached = false
tag_disabled = false
format = '[$tag #$hash ]($style)'
style = 'fg:color_red bg:color_mantle'
commit_hash_length = 4
tag_symbol = ''



[c]
symbol = 'gcc: '
format = '[$symbol($version )]($style)'
style = 'fg:color_lavender bg:color_mantle'

[custom.cpp-gcc]
symbol = 'g++: '
format = '[$symbol($output )]($style)'
style = 'fg:color_lavender bg:color_mantle'
detect_extensions = ['cpp', 'c++', 'hpp', 'h++']
command = "g++ --version | tr ' ' '\n' | head -n 3 | tail -n 1"

[docker_context]
symbol = ' '
format = '[$symbol$context ]($style)'
style = 'fg:color_blue bg:color_mantle'

[golang]
symbol = ''
format = '[$symbol ($version )]($style)'
style = 'fg:color_lavender bg:color_mantle'

[lua]
symbol = ''
format = '[$symbol ($version )]($style)'
style = 'fg:color_lavender bg:color_mantle'

[nodejs]
symbol = ''
format = '[$symbol ($version )]($style)'
style = 'fg:color_lavender bg:color_mantle'

[python]
symbol = ' '
format =  '[ ${symbol}${pyenv_prefix}(${version} )(\($virtualenv\) )]($style)'
style = 'fg:color_lavender bg:color_mantle'

[rust]
symbol = ''
format = '[$symbol ($version )]($style)'
style = 'fg:color_lavender bg:color_mantle'

[cmake]
format = '[$symbol($version )]($style)'
style = 'fg:color_lavender bg:color_mantle'






[line_break]
disabled = false

[status]
disabled = false
style = 'fg:color_text bg:color_base'
format = """
[\
(Exit code: [$maybe_int]($style fg:color_red))\
(Exit status: [$common_meaning]($style fg:color_peach))\
(Signal: [$signal_name]($style fg:color_yellow))]\
($style)\
"""

[character]
format = ' '
disabled = false

[os.symbols]
Windows = "󰍲 "
Ubuntu = "󰕈 "
SUSE = " "
Raspbian = "󰐿 "
Mint = "󰣭 "
Macos = "󰀵 "
Manjaro = " "
Linux = "󰌽 "
Gentoo = "󰣨 "
Fedora = "󰣛 "
Alpine = " "
Amazon = " "
Android = " "
Arch = "󰣇 "
Artix = "󰣇 "
CentOS = " "
Debian = "󰣚 "
Redhat = "󱄛 "
RedHatEnterprise = "󱄛 "

[palettes.catppuccin_macchiato]
color_rosewater = "#f4dbd6"
color_flamingo =  "#f0c6c6"
color_pink =      "#f5bde6"
color_mauve =     "#c6a0f6"
color_red =       "#ed8796"
color_maroon =    "#ee99a0"
color_peach =     "#f5a97f"
color_yellow =    "#eed49f"
color_green =     "#a6da95"
color_teal =      "#8bd5ca"
color_sky =       "#91d7e3"
color_sapphire =  "#7dc4e4"
color_blue =      "#8aadf4"
color_lavender =  "#b7bdf8"
color_text = "#cad3f5"
color_subtext1 = "#b8c0e0"
color_subtext0 = "#a5adcb"
color_overlay2 = "#939ab7"
color_overlay1 = "#8087a2"
color_overlay0 = "#6e738d"
color_surface2 = "#5b6078"
color_surface1 = "#494d64"
color_surface0 = "#363a4f"
color_base = "#24273a"
color_mantle = "#1e2030"
color_crust = "#181926"
